---
title : "Significativité des différences entre les valeurs maximales de précision moyenne (max_avg_gen_accuracy) des connaissances respectivement atteintes dans les  populations d'agents définies selon la durée de simulation (200001 itérations) ou la durée de vie des agents (7501 ;15001 ; 30001)"
output:
  html_document
    
---

```{r, echo=FALSE, results='asis', warning=FALSE}

library(ggplot2)
library(readr)
library(knitr)
library(kableExtra)
library(dplyr)

create_summary_table <- function() {
  # Liste des URLs des fichiers
  urls <- c("https://raw.githubusercontent.com/NinaComete/DOTG/master/200001-1-random/average.csv",
            "https://raw.githubusercontent.com/NinaComete/DOTG/master/200001-0.8-random/average.csv",
            "https://raw.githubusercontent.com/NinaComete/DOTG/master/200001-0.6-random/average.csv",
            "https://raw.githubusercontent.com/NinaComete/DOTG/master/200001-0.4-random/average.csv",
            "https://raw.githubusercontent.com/NinaComete/DOTG/master/200001-0.2-random/average.csv",
            "https://raw.githubusercontent.com/NinaComete/DOTG/master/5001-1-random/average.csv",
            "https://raw.githubusercontent.com/NinaComete/DOTG/master/5001-0.8-random/average.csv",
            "https://raw.githubusercontent.com/NinaComete/DOTG/master/5001-0.6-random/average.csv",
            "https://raw.githubusercontent.com/NinaComete/DOTG/master/5001-0.4-random/average.csv",
            "https://raw.githubusercontent.com/NinaComete/DOTG/master/5001-0.2-random/average.csv",
            "https://raw.githubusercontent.com/NinaComete/DOTG/master/10001-1-random/average.csv",
            "https://raw.githubusercontent.com/NinaComete/DOTG/master/10001-0.8-random/average.csv",
            "https://raw.githubusercontent.com/NinaComete/DOTG/master/10001-0.6-random/average.csv",
            "https://raw.githubusercontent.com/NinaComete/DOTG/master/10001-0.4-random/average.csv",
            "https://raw.githubusercontent.com/NinaComete/DOTG/master/10001-0.2-random/average.csv",
            "https://raw.githubusercontent.com/NinaComete/DOTG/master/20001-1-random/average.csv",
            "https://raw.githubusercontent.com/NinaComete/DOTG/master/20001-0.8-random/average.csv",
            "https://raw.githubusercontent.com/NinaComete/DOTG/master/20001-0.6-random/average.csv",
            "https://raw.githubusercontent.com/NinaComete/DOTG/master/20001-0.4-random/average.csv",
            "https://raw.githubusercontent.com/NinaComete/DOTG/master/20001-0.2-random/average.csv")
  
  # Initialisation des vecteurs
  duree_de_vie_ou_de_simulation <- c()
  max_avg_gen_accuracies <- c()
  max_avg_gen_accuracy_ranks <- c()
  max_avg_gen_srates <- c()
  max_avg_gen_srate_ranks <- c()
  last_ranks <- c()
  last_value_accuracies <- c()
  last_value_srates <- c()
  
  # Boucle sur chaque URL
  for (url in urls) {
    # Charger les données
    data <- read.csv(url, header = TRUE, sep = " ")
    
    # Trouver l'indice où avg.genAccuracy est maximale
    max_index_accuracy <- which.max(data$avg.genAccuracy)
    max_value_accuracy <- data$avg.genAccuracy[max_index_accuracy]
    max_rank_accuracy <- data$rank[max_index_accuracy]
    
    # Trouver l'indice où avg.genSrate est maximale
    max_index_srate <- which.max(data$avg.genSrate)
    max_value_srate <- data$avg.genSrate[max_index_srate]
    max_rank_srate <- data$rank[max_index_srate]
    
    # Trouver l'indice de la dernière itération
    last_index <- nrow(data)
    last_value_accuracy <- data$avg.genAccuracy[last_index]
    last_value_srate <- data$avg.genSrate[last_index]
    
    # Calcul de la durée de simulation ou de la durée de vie en fonction de l'URL
    if (grepl("200001", url)) {
      duree_de_vie_ou_de_simulation_actuelle <- "200001"
    } else if (grepl("5001", url)) {
      duree_de_vie_ou_de_simulation_actuelle <- "7501"
    } else if (grepl("10001", url)) {
      duree_de_vie_ou_de_simulation_actuelle <- "15001"
    } else if (grepl("20001", url)) {
      duree_de_vie_ou_de_simulation_actuelle <- "30001"
    }
    
    # Ajouter les informations aux vecteurs
    duree_de_vie_ou_de_simulation <- c(duree_de_vie_ou_de_simulation, duree_de_vie_ou_de_simulation_actuelle)
    max_avg_gen_accuracies <- c(max_avg_gen_accuracies, max_value_accuracy)
    max_avg_gen_accuracy_ranks <- c(max_avg_gen_accuracy_ranks, max_rank_accuracy)
    max_avg_gen_srates <- c(max_avg_gen_srates, max_value_srate)
    max_avg_gen_srate_ranks <- c(max_avg_gen_srate_ranks, max_rank_srate)
    last_ranks <- c(last_ranks, data$rank[last_index])
    last_value_accuracies <- c(last_value_accuracies, last_value_accuracy)
    last_value_srates <- c(last_value_srates, last_value_srate)
  }
  
  # Création du dataframe
  tableau_periodes_random <- data.frame(duree_de_vie_ou_de_simulation = duree_de_vie_ou_de_simulation,
                                        max_avg_gen_accuracy = max_avg_gen_accuracies,
                                        max_avg_gen_accuracy_rank = max_avg_gen_accuracy_ranks,
                                        max_avg_gen_srate = max_avg_gen_srates,
                                        max_avg_gen_srate_rank = max_avg_gen_srate_ranks,
                                        last_rank = last_ranks,
                                        last_value_accuracy = last_value_accuracies,
                                        last_value_srate = last_value_srates)
  
  return(tableau_periodes_random)
}

# Créer le tableau récapitulatif
tableau_periodes_random <- create_summary_table()


# ANOVA pour tableau_periodes_random ----
model <- aov(max_avg_gen_accuracy ~ duree_de_vie_ou_de_simulation, data = tableau_periodes_random)

# Effectuer le test de Tukey
tukey_test <- TukeyHSD(model)

# Afficher les résultats du test de Tukey avec kable() en format HTML
tukey_results <- as.data.frame(tukey_test$`duree_de_vie_ou_de_simulation`)
colnames(tukey_results) <- c("Différence entre les moyennes des groupes comparés (diff)", 
                             "Limite inférieure de l'intervalle de confiance à 95% pour la différence entre les moyennes", 
                             "Limite supérieure de l'intervalle de confiance à 95% pour la différence entre les moyennes", 
                             "Probabilité ajustée pour chaque comparaison (significatif si <0.05)")

print(kable(tukey_results, format = "html", caption = "Résultats du test de Tukey (HSD) appliqué aux valeurs maximales de précision moyenne des connaissances atteintes dans les différentes populations définies par la durée de la simulation (200001 itérations) ou par la durée de vie des agents (7501, 10001 ou 20001 itérations)",
      col.width = "100px", text.font = "10pt"))
 
```


```{r, echo=FALSE, results='asis', warning=FALSE}

library(ggplot2)
library(readr)
library(knitr)
library(kableExtra)
library(dplyr)

# Tableau des moyennes par durée de vie ou de simulation ----

# Regrouper les données par la variable "duree_de_vie_ou_de_simulation_de_vie"
grouped_data <- tableau_periodes_random %>%
  group_by(duree_de_vie_ou_de_simulation)

# Calculer les moyennes pour chaque groupe
mean_data <- grouped_data %>%
  summarise(mean_max_avg_gen_accuracy = mean(max_avg_gen_accuracy),
            mean_max_avg_gen_srate = mean(max_avg_gen_srate))

# Afficher le tableau des moyennes pour chaque groupe

print(kable(mean_data, format = "html", caption = "Tableau récaitulatif des valeurs maximales de précision moyenne des connaissances atteintes dans les différentes populations définies par la durée de la simulation (200001 itérations) ou par la durée de vie des agents (7501, 10001 ou 20001 itérations).",
      col.width = "100px", text.font = "10pt"))
 

``` 
